package org.cem.entities;
// Generated 12-oct-2017 0:48:22 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Alumno generated by hbm2java
 */
public class Alumno  implements java.io.Serializable {


     private int rutPersona;
     private Persona persona;
     private BigDecimal numeroMatricula;
     private Date fechaMatricula;
     private Set certificados = new HashSet(0);
     private Set calificacions = new HashSet(0);
     private Set postulacionesAlumnoses = new HashSet(0);

    public Alumno() {
    }

	
    public Alumno(Persona persona, BigDecimal numeroMatricula, Date fechaMatricula) {
        this.persona = persona;
        this.numeroMatricula = numeroMatricula;
        this.fechaMatricula = fechaMatricula;
    }
    public Alumno(Persona persona, BigDecimal numeroMatricula, Date fechaMatricula, Set certificados, Set calificacions, Set postulacionesAlumnoses) {
       this.persona = persona;
       this.numeroMatricula = numeroMatricula;
       this.fechaMatricula = fechaMatricula;
       this.certificados = certificados;
       this.calificacions = calificacions;
       this.postulacionesAlumnoses = postulacionesAlumnoses;
    }
   
    public int getRutPersona() {
        return this.rutPersona;
    }
    
    public void setRutPersona(int rutPersona) {
        this.rutPersona = rutPersona;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public BigDecimal getNumeroMatricula() {
        return this.numeroMatricula;
    }
    
    public void setNumeroMatricula(BigDecimal numeroMatricula) {
        this.numeroMatricula = numeroMatricula;
    }
    public Date getFechaMatricula() {
        return this.fechaMatricula;
    }
    
    public void setFechaMatricula(Date fechaMatricula) {
        this.fechaMatricula = fechaMatricula;
    }
    public Set getCertificados() {
        return this.certificados;
    }
    
    public void setCertificados(Set certificados) {
        this.certificados = certificados;
    }
    public Set getCalificacions() {
        return this.calificacions;
    }
    
    public void setCalificacions(Set calificacions) {
        this.calificacions = calificacions;
    }
    public Set getPostulacionesAlumnoses() {
        return this.postulacionesAlumnoses;
    }
    
    public void setPostulacionesAlumnoses(Set postulacionesAlumnoses) {
        this.postulacionesAlumnoses = postulacionesAlumnoses;
    }




}


