package org.cem.entities;
// Generated 12-oct-2017 0:48:22 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.sql.Blob;
import java.util.Date;

/**
 * Antecedente generated by hbm2java
 */
public class Antecedente  implements java.io.Serializable {


     private BigDecimal codigo;
     private FamiliaAnfitriona familiaAnfitriona;
     private String descripcion;
     private Date fechaCaducidad;
     private Blob documento;

    public Antecedente() {
    }

	
    public Antecedente(BigDecimal codigo, FamiliaAnfitriona familiaAnfitriona, String descripcion, Date fechaCaducidad) {
        this.codigo = codigo;
        this.familiaAnfitriona = familiaAnfitriona;
        this.descripcion = descripcion;
        this.fechaCaducidad = fechaCaducidad;
    }
    public Antecedente(BigDecimal codigo, FamiliaAnfitriona familiaAnfitriona, String descripcion, Date fechaCaducidad, Blob documento) {
       this.codigo = codigo;
       this.familiaAnfitriona = familiaAnfitriona;
       this.descripcion = descripcion;
       this.fechaCaducidad = fechaCaducidad;
       this.documento = documento;
    }
   
    public BigDecimal getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(BigDecimal codigo) {
        this.codigo = codigo;
    }
    public FamiliaAnfitriona getFamiliaAnfitriona() {
        return this.familiaAnfitriona;
    }
    
    public void setFamiliaAnfitriona(FamiliaAnfitriona familiaAnfitriona) {
        this.familiaAnfitriona = familiaAnfitriona;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Date getFechaCaducidad() {
        return this.fechaCaducidad;
    }
    
    public void setFechaCaducidad(Date fechaCaducidad) {
        this.fechaCaducidad = fechaCaducidad;
    }
    public Blob getDocumento() {
        return this.documento;
    }
    
    public void setDocumento(Blob documento) {
        this.documento = documento;
    }




}


