package org.cem.entities;
// Generated 12-oct-2017 0:48:22 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Asignatura generated by hbm2java
 */
public class Asignatura  implements java.io.Serializable {


     private BigDecimal codigo;
     private Docente docente;
     private String nombreAsignatura;
     private String descripcion;
     private Long cupos;
     private Set programas = new HashSet(0);
     private Set calificacions = new HashSet(0);

    public Asignatura() {
    }

	
    public Asignatura(BigDecimal codigo, Docente docente, String nombreAsignatura) {
        this.codigo = codigo;
        this.docente = docente;
        this.nombreAsignatura = nombreAsignatura;
    }
    public Asignatura(BigDecimal codigo, Docente docente, String nombreAsignatura, String descripcion, Long cupos, Set programas, Set calificacions) {
       this.codigo = codigo;
       this.docente = docente;
       this.nombreAsignatura = nombreAsignatura;
       this.descripcion = descripcion;
       this.cupos = cupos;
       this.programas = programas;
       this.calificacions = calificacions;
    }
   
    public BigDecimal getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(BigDecimal codigo) {
        this.codigo = codigo;
    }
    public Docente getDocente() {
        return this.docente;
    }
    
    public void setDocente(Docente docente) {
        this.docente = docente;
    }
    public String getNombreAsignatura() {
        return this.nombreAsignatura;
    }
    
    public void setNombreAsignatura(String nombreAsignatura) {
        this.nombreAsignatura = nombreAsignatura;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Long getCupos() {
        return this.cupos;
    }
    
    public void setCupos(Long cupos) {
        this.cupos = cupos;
    }
    public Set getProgramas() {
        return this.programas;
    }
    
    public void setProgramas(Set programas) {
        this.programas = programas;
    }
    public Set getCalificacions() {
        return this.calificacions;
    }
    
    public void setCalificacions(Set calificacions) {
        this.calificacions = calificacions;
    }




}


