package org.cem.entities;
// Generated 12-oct-2017 0:48:22 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * CentroEstudiosLocal generated by hbm2java
 */
public class CentroEstudiosLocal  implements java.io.Serializable {


     private int rutPersona;
     private Persona persona;
     private byte estaAcreditada;
     private Set postulacionesCels = new HashSet(0);

    public CentroEstudiosLocal() {
    }

	
    public CentroEstudiosLocal(Persona persona, byte estaAcreditada) {
        this.persona = persona;
        this.estaAcreditada = estaAcreditada;
    }
    public CentroEstudiosLocal(Persona persona, byte estaAcreditada, Set postulacionesCels) {
       this.persona = persona;
       this.estaAcreditada = estaAcreditada;
       this.postulacionesCels = postulacionesCels;
    }
   
    public int getRutPersona() {
        return this.rutPersona;
    }
    
    public void setRutPersona(int rutPersona) {
        this.rutPersona = rutPersona;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public byte getEstaAcreditada() {
        return this.estaAcreditada;
    }
    
    public void setEstaAcreditada(byte estaAcreditada) {
        this.estaAcreditada = estaAcreditada;
    }
    public Set getPostulacionesCels() {
        return this.postulacionesCels;
    }
    
    public void setPostulacionesCels(Set postulacionesCels) {
        this.postulacionesCels = postulacionesCels;
    }




}


