package org.cem.entities;
// Generated 12-oct-2017 0:48:22 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Docente generated by hbm2java
 */
public class Docente  implements java.io.Serializable {


     private int rutPersona;
     private Persona persona;
     private String estado;
     private String observaciones;
     private Set asignaturas = new HashSet(0);

    public Docente() {
    }

	
    public Docente(Persona persona) {
        this.persona = persona;
    }
    public Docente(Persona persona, String estado, String observaciones, Set asignaturas) {
       this.persona = persona;
       this.estado = estado;
       this.observaciones = observaciones;
       this.asignaturas = asignaturas;
    }
   
    public int getRutPersona() {
        return this.rutPersona;
    }
    
    public void setRutPersona(int rutPersona) {
        this.rutPersona = rutPersona;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }
    public Set getAsignaturas() {
        return this.asignaturas;
    }
    
    public void setAsignaturas(Set asignaturas) {
        this.asignaturas = asignaturas;
    }

    
}


