package org.cem.entities;
// Generated 12-oct-2017 0:48:22 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * FamiliaAnfitriona generated by hbm2java
 */
public class FamiliaAnfitriona  implements java.io.Serializable {


     private int rutPersona;
     private Persona persona;
     private Short cantidadIntegrantes;
     private String estado;
     private Set antecedentes = new HashSet(0);

    public FamiliaAnfitriona() {
    }

	
    public FamiliaAnfitriona(Persona persona, String estado) {
        this.persona = persona;
        this.estado = estado;
    }
    public FamiliaAnfitriona(Persona persona, Short cantidadIntegrantes, String estado, Set antecedentes) {
       this.persona = persona;
       this.cantidadIntegrantes = cantidadIntegrantes;
       this.estado = estado;
       this.antecedentes = antecedentes;
    }
   
    public int getRutPersona() {
        return this.rutPersona;
    }
    
    public void setRutPersona(int rutPersona) {
        this.rutPersona = rutPersona;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public Short getCantidadIntegrantes() {
        return this.cantidadIntegrantes;
    }
    
    public void setCantidadIntegrantes(Short cantidadIntegrantes) {
        this.cantidadIntegrantes = cantidadIntegrantes;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getAntecedentes() {
        return this.antecedentes;
    }
    
    public void setAntecedentes(Set antecedentes) {
        this.antecedentes = antecedentes;
    }




}


