package org.cem.entities;
// Generated 12-oct-2017 0:48:22 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * PostulacionesAlumnos generated by hbm2java
 */
public class PostulacionesAlumnos  implements java.io.Serializable {


     private BigDecimal codigo;
     private Alumno alumno;
     private Programa programa;
     private Date fechaInscripcion;
     private String estado;

    public PostulacionesAlumnos() {
    }

    public PostulacionesAlumnos(BigDecimal codigo, Alumno alumno, Programa programa, Date fechaInscripcion, String estado) {
       this.codigo = codigo;
       this.alumno = alumno;
       this.programa = programa;
       this.fechaInscripcion = fechaInscripcion;
       this.estado = estado;
    }
   
    public BigDecimal getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(BigDecimal codigo) {
        this.codigo = codigo;
    }
    public Alumno getAlumno() {
        return this.alumno;
    }
    
    public void setAlumno(Alumno alumno) {
        this.alumno = alumno;
    }
    public Programa getPrograma() {
        return this.programa;
    }
    
    public void setPrograma(Programa programa) {
        this.programa = programa;
    }
    public Date getFechaInscripcion() {
        return this.fechaInscripcion;
    }
    
    public void setFechaInscripcion(Date fechaInscripcion) {
        this.fechaInscripcion = fechaInscripcion;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


