package org.cem.entities;
// Generated 12-oct-2017 0:48:22 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * PostulacionesCel generated by hbm2java
 */
public class PostulacionesCel  implements java.io.Serializable {


     private BigDecimal codigo;
     private CentroEstudiosLocal centroEstudiosLocal;
     private Programa programa;
     private Date fechaInscripcion;
     private String estado;

    public PostulacionesCel() {
    }

    public PostulacionesCel(BigDecimal codigo, CentroEstudiosLocal centroEstudiosLocal, Programa programa, Date fechaInscripcion, String estado) {
       this.codigo = codigo;
       this.centroEstudiosLocal = centroEstudiosLocal;
       this.programa = programa;
       this.fechaInscripcion = fechaInscripcion;
       this.estado = estado;
    }
   
    public BigDecimal getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(BigDecimal codigo) {
        this.codigo = codigo;
    }
    public CentroEstudiosLocal getCentroEstudiosLocal() {
        return this.centroEstudiosLocal;
    }
    
    public void setCentroEstudiosLocal(CentroEstudiosLocal centroEstudiosLocal) {
        this.centroEstudiosLocal = centroEstudiosLocal;
    }
    public Programa getPrograma() {
        return this.programa;
    }
    
    public void setPrograma(Programa programa) {
        this.programa = programa;
    }
    public Date getFechaInscripcion() {
        return this.fechaInscripcion;
    }
    
    public void setFechaInscripcion(Date fechaInscripcion) {
        this.fechaInscripcion = fechaInscripcion;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


